---
version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.3.0
    container_name: selenium-hub
    environment:
      GRID_MAX_SESSION: 10
    ports:
      - '4442-4444:4442-4444'

  chrome:
    image: selenium/node-chrome:4.3.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SCREEN_HEIGHT: 1200
      SCREEN_WIDTH: 1920
      NODE_MAX_INSTANCES: 10
      NODE_MAX_SESSION: 10
      VNC_NO_PASSWORD: 1
    ports:
      - 5900:5900
